version: "3"

services:
  maadb-ps-db:
    image: postgres:latest
    container_name: maadb-ps-db
    ports:
      - "5433:5432"
    env_file:
      - postgres.env
    restart: always
    volumes:
      - database-data:/usr/local/var/postgreSQL

volumes:
  database-data:








